// K18: renders api/v1/insights.json — a static artefact generated by
// tools/build-insights.mjs from data/schemes.json and data/slots.json
// alone (see that file's header for the exact method and why a literal
// cartesian product across every referenced slot isn't used). No
// service call, no citizen data — every number here is either read
// straight from the fetched JSON or computed from it in this file.
//
// K8: bilingual — re-renders on 'kisan:langchange', same as every other
// static-core surface.
import { resolvePath } from '../../js/paths.js';
import { getLang, t } from '../../js/i18n.js';
import { labelFor, labelForEn } from '../../js/assemble.js';

function el(tag, className, text) {
  const e = document.createElement(tag);
  if (className) e.className = className;
  if (text !== undefined && text !== null) e.textContent = text;
  return e;
}

function pct(n, total) {
  return total > 0 ? Math.round((n / total) * 100) : 0;
}

function nameFor(scheme) {
  return getLang() === 'en' && scheme.name_en ? scheme.name_en : scheme.name_hi;
}

function renderSchemeBar(scheme) {
  const row = el('div', 'insight-scheme-row');
  const head = el('div', 'insight-scheme-head');
  head.appendChild(el('span', getLang() === 'hi' ? 'hi' : '', nameFor(scheme)));
  head.appendChild(el('span', `badge ${scheme.reachable ? '' : 'bg-halt'}`.trim(),
    scheme.reachable ? t('insights.reachable') : t('insights.unreachable')));
  row.appendChild(head);

  const bar = el('div', 'insight-bar');
  const eligiblePct = pct(scheme.eligible_profiles, scheme.profiles_tested);
  const notEligiblePct = pct(scheme.not_eligible_profiles, scheme.profiles_tested);
  const needInfoPct = Math.max(0, 100 - eligiblePct - notEligiblePct);
  bar.appendChild(el('span', 'insight-bar-segment insight-bar-eligible', ''));
  bar.querySelector('.insight-bar-eligible').style.width = `${eligiblePct}%`;
  const notEl = el('span', 'insight-bar-segment insight-bar-not-eligible', '');
  notEl.style.width = `${notEligiblePct}%`;
  bar.appendChild(notEl);
  const needEl = el('span', 'insight-bar-segment insight-bar-need-info', '');
  needEl.style.width = `${needInfoPct}%`;
  bar.appendChild(needEl);
  row.appendChild(bar);

  const cls = getLang() === 'hi' ? 'citation hi' : 'citation';
  row.appendChild(el('p', cls,
    `${scheme.profiles_tested} ${t('insights.out_of_profiles')} — ${t('chat.verdict_eligible')} ${scheme.eligible_profiles}, ${t('chat.verdict_not_eligible')} ${scheme.not_eligible_profiles}, ${t('chat.verdict_need_info')} ${scheme.need_more_info_profiles} (${t('insights.reference_slots')}: ${scheme.referenced_slots.join(', ')})`));
  return row;
}

function renderSlotRanking(container, ranking) {
  const top = ranking.slice(0, 8);
  const maxShare = top.length > 0 ? top[0].share : 1;
  const cls = getLang() === 'hi' ? 'hi' : '';
  top.forEach((entry) => {
    const row = el('div', 'insight-scheme-row');
    const head = el('div', 'insight-scheme-head');
    const slotLabel = getLang() === 'en' ? labelForEn(entry.slot) : labelFor(entry.slot);
    head.appendChild(el('span', cls, slotLabel));
    head.appendChild(el('span', 'citation', `${Math.round(entry.share * 1000) / 10}%`));
    row.appendChild(head);
    const bar = el('div', 'insight-bar');
    const seg = el('span', 'insight-bar-segment insight-bar-not-eligible', '');
    seg.style.width = `${pct(entry.share, maxShare)}%`;
    bar.appendChild(seg);
    row.appendChild(bar);
    container.appendChild(row);
  });
}

async function init() {
  const summaryEl = document.getElementById('insight-summary');
  const leadTextEl = document.getElementById('insight-lead-text');
  const schemesEl = document.getElementById('insight-schemes');
  const slotsEl = document.getElementById('insight-slots');
  const headlineEl = document.getElementById('insight-headline');
  const linkEl = document.getElementById('insights-json-link');
  linkEl.href = resolvePath('api/v1/insights.json');

  let data;
  try {
    const res = await fetch(resolvePath('api/v1/insights.json'));
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    data = await res.json();
  } catch (err) {
    console.error('insights: failed to load api/v1/insights.json:', err);
    summaryEl.innerHTML = '';
    summaryEl.appendChild(el('p', 'hi term-warning', t('insights.load_error')));
    return;
  }

  const render = () => {
    const lang = getLang();
    const cls = lang === 'hi' ? 'hi' : '';
    const methodologyNote = lang === 'en' && data.methodology_note_en ? data.methodology_note_en : data.methodology_note_hi;

    // T2: two real numbers, not one bare total — data.agriculture_count /
    // related_welfare_count come straight from tools/build-insights.mjs,
    // which reads scheme_group off each record, same as everywhere else.
    const countLine = data.agriculture_count !== undefined
      ? `${data.agriculture_count} ${t('insights.agriculture_label')} + ${data.related_welfare_count} ${t('insights.related_welfare_label')} = ${data.scheme_count} ${t('insights.generated_summary')}`
      : `${data.scheme_count} ${t('insights.generated_summary')}`;
    summaryEl.innerHTML = '';
    summaryEl.appendChild(el('p', cls,
      `${countLine} · ${t('insights.built_at')}: ${new Date(data.generated_at).toLocaleString(lang === 'en' ? 'en-IN' : 'hi-IN')}`));
    summaryEl.appendChild(el('p', `citation ${cls}`.trim(), methodologyNote));

    // T9: the good finding leads the page — 0 unreachable schemes is a
    // real, checkable claim (every eligibility condition in the registry
    // actually resolves), not filler, so it gets the first section rather
    // than a clause buried in the summary line. Only claims "good" when
    // that's actually true; a genuine unreachable scheme still turns this
    // red and names it, exactly as the old inline warning did.
    const leadSection = document.getElementById('insight-lead');
    const unreachable = data.unreachable_scheme_ids;
    leadSection.classList.remove('bg-verdict', 'bg-halt');
    if (unreachable.length === 0) {
      leadSection.classList.add('bg-verdict');
      leadSection.querySelector('.card-icon').textContent = '✅';
      leadTextEl.textContent = lang === 'en'
        ? `All ${data.scheme_count} schemes are fully reachable by the engine — none is blocked by a broken condition in the data.`
        : `सभी ${data.scheme_count} योजनाएं इंजन से पूरी तरह जांची जा सकती हैं — डेटा में किसी टूटी शर्त के कारण कोई भी अगम्य नहीं है।`;
    } else {
      leadSection.classList.add('bg-halt');
      leadSection.querySelector('.card-icon').textContent = '⚠';
      leadTextEl.textContent = `${t('insights.unreachable_warning')}: ${unreachable.join(', ')}`;
    }

    schemesEl.innerHTML = '';
    data.per_scheme
      .slice()
      .sort((a, b) => (a.reachable === b.reachable ? 0 : a.reachable ? 1 : -1))
      .forEach((scheme) => schemesEl.appendChild(renderSchemeBar(scheme)));

    slotsEl.innerHTML = '';
    renderSlotRanking(slotsEl, data.slot_block_ranking);

    const h = data.headline_profile_analysis;
    headlineEl.innerHTML = '';
    const grid = el('div', 'stat-grid');
    const tile = (value, label) => {
      const tl = el('div', 'stat-tile');
      tl.appendChild(el('div', 'stat-tile-value', String(value)));
      tl.appendChild(el('div', `stat-tile-label ${cls}`.trim(), label));
      return tl;
    };
    grid.appendChild(tile(h.total_profiles, `${t('insights.stat_total')} (${h.dimensions.join(' × ')})`));
    grid.appendChild(tile(h.already_eligible_for_some_profiles, t('insights.stat_eligible_some')));
    grid.appendChild(tile(h.still_undetermined_profiles, t('insights.stat_undetermined')));
    grid.appendChild(tile(h.definitely_zero_eligible_profiles, t('insights.stat_zero_eligible')));
    headlineEl.appendChild(grid);
    headlineEl.appendChild(el('p', `citation ${cls}`.trim(), t('insights.zero_eligible_note')));
    if (h.occupations_always_zero_eligible.length > 0) {
      const list = el('ul', 'doc-list');
      h.occupations_always_zero_eligible.forEach((occ) => {
        list.appendChild(el('li', cls, lang === 'en' && occ.label_en ? occ.label_en : occ.label_hi));
      });
      headlineEl.appendChild(el('p', `${cls} doc-list-title`.trim(), t('insights.occupations_zero_title')));
      headlineEl.appendChild(list);
    } else {
      headlineEl.appendChild(el('p', `citation ${cls}`.trim(), t('insights.occupations_zero_none')));
    }
  };

  render();
  window.addEventListener('kisan:langchange', render);
}

init();
