// K18: renders api/v1/insights.json — a static artefact generated by
// tools/build-insights.mjs from data/schemes.json and data/slots.json
// alone (see that file's header for the exact method and why a literal
// cartesian product across every referenced slot isn't used). No
// service call, no citizen data — every number here is either read
// straight from the fetched JSON or computed from it in this file.
import { resolvePath } from '../../js/paths.js';

function el(tag, className, text) {
  const e = document.createElement(tag);
  if (className) e.className = className;
  if (text !== undefined && text !== null) e.textContent = text;
  return e;
}

function pct(n, total) {
  return total > 0 ? Math.round((n / total) * 100) : 0;
}

function renderSchemeBar(scheme) {
  const row = el('div', 'insight-scheme-row');
  const head = el('div', 'insight-scheme-head');
  head.appendChild(el('span', 'hi', scheme.name_hi));
  head.appendChild(el('span', `hi badge ${scheme.reachable ? '' : 'bg-halt'}`.trim(),
    scheme.reachable ? '✅ पहुंच योग्य' : '⛔ अप्राप्य'));
  row.appendChild(head);

  const bar = el('div', 'insight-bar');
  const eligiblePct = pct(scheme.eligible_profiles, scheme.profiles_tested);
  const notEligiblePct = pct(scheme.not_eligible_profiles, scheme.profiles_tested);
  const needInfoPct = Math.max(0, 100 - eligiblePct - notEligiblePct);
  bar.appendChild(el('span', 'insight-bar-segment insight-bar-eligible', ''));
  bar.querySelector('.insight-bar-eligible').style.width = `${eligiblePct}%`;
  const notEl = el('span', 'insight-bar-segment insight-bar-not-eligible', '');
  notEl.style.width = `${notEligiblePct}%`;
  bar.appendChild(notEl);
  const needEl = el('span', 'insight-bar-segment insight-bar-need-info', '');
  needEl.style.width = `${needInfoPct}%`;
  bar.appendChild(needEl);
  row.appendChild(bar);

  row.appendChild(el('p', 'citation hi',
    `${scheme.profiles_tested} यथार्थ प्रोफ़ाइलों में से — पात्र ${scheme.eligible_profiles}, अपात्र ${scheme.not_eligible_profiles}, जानकारी चाहिए ${scheme.need_more_info_profiles} (सन्दर्भ स्लॉट: ${scheme.referenced_slots.join(', ')})`));
  return row;
}

function renderSlotRanking(container, ranking) {
  const top = ranking.slice(0, 8);
  const maxShare = top.length > 0 ? top[0].share : 1;
  top.forEach((entry) => {
    const row = el('div', 'insight-scheme-row');
    const head = el('div', 'insight-scheme-head');
    head.appendChild(el('span', 'hi', entry.slot));
    head.appendChild(el('span', 'citation hi', `${Math.round(entry.share * 1000) / 10}%`));
    row.appendChild(head);
    const bar = el('div', 'insight-bar');
    const seg = el('span', 'insight-bar-segment insight-bar-not-eligible', '');
    seg.style.width = `${pct(entry.share, maxShare)}%`;
    bar.appendChild(seg);
    row.appendChild(bar);
    container.appendChild(row);
  });
}

async function init() {
  const summaryEl = document.getElementById('insight-summary');
  const schemesEl = document.getElementById('insight-schemes');
  const slotsEl = document.getElementById('insight-slots');
  const headlineEl = document.getElementById('insight-headline');
  const linkEl = document.getElementById('insights-json-link');
  linkEl.href = resolvePath('api/v1/insights.json');

  let data;
  try {
    const res = await fetch(resolvePath('api/v1/insights.json'));
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    data = await res.json();
  } catch (err) {
    console.error('insights: failed to load api/v1/insights.json:', err);
    summaryEl.innerHTML = '';
    summaryEl.appendChild(el('p', 'hi term-warning', '⚠ आंकड़े अभी लोड नहीं हो सके।'));
    return;
  }

  summaryEl.innerHTML = '';
  summaryEl.appendChild(el('p', 'hi',
    `${data.scheme_count} योजनाओं का विश्लेषण · अप्राप्य: ${data.unreachable_scheme_ids.length} · बना: ${new Date(data.generated_at).toLocaleString('hi-IN')}`));
  summaryEl.appendChild(el('p', 'hi citation', data.methodology_note_hi));
  if (data.unreachable_scheme_ids.length > 0) {
    const warn = el('p', 'hi term-warning', `⚠ अप्राप्य योजना(एं): ${data.unreachable_scheme_ids.join(', ')}`);
    summaryEl.appendChild(warn);
  }

  schemesEl.innerHTML = '';
  data.per_scheme
    .slice()
    .sort((a, b) => (a.reachable === b.reachable ? 0 : a.reachable ? 1 : -1))
    .forEach((scheme) => schemesEl.appendChild(renderSchemeBar(scheme)));

  slotsEl.innerHTML = '';
  renderSlotRanking(slotsEl, data.slot_block_ranking);

  const h = data.headline_profile_analysis;
  headlineEl.innerHTML = '';
  const grid = el('div', 'stat-grid');
  const tile = (value, label) => {
    const t = el('div', 'stat-tile');
    t.appendChild(el('div', 'stat-tile-value', String(value)));
    t.appendChild(el('div', 'stat-tile-label hi', label));
    return t;
  };
  grid.appendChild(tile(h.total_profiles, `कुल प्रोफ़ाइल (${h.dimensions.join(' × ')})`));
  grid.appendChild(tile(h.already_eligible_for_some_profiles, 'पहले से किसी योजना के लिए पात्र'));
  grid.appendChild(tile(h.still_undetermined_profiles, 'अभी अनिर्णीत — और जानकारी चाहिए'));
  grid.appendChild(tile(h.definitely_zero_eligible_profiles, 'निश्चित रूप से शून्य-पात्र'));
  headlineEl.appendChild(grid);
  headlineEl.appendChild(el('p', 'hi citation',
    '"निश्चित रूप से शून्य-पात्र" का मतलब है: इंजन के तीन-मान तर्क में, एक बार जो शर्त झूठी सिद्ध हो जाए, वह आगे कोई भी जानकारी जोड़ने से सच नहीं बन सकती — इसलिए यह आंकड़ा अनुमान नहीं, स्थायी तथ्य है।'));
  if (h.occupations_always_zero_eligible.length > 0) {
    const list = el('ul', 'doc-list');
    h.occupations_always_zero_eligible.forEach((occ) => list.appendChild(el('li', 'hi', occ)));
    headlineEl.appendChild(el('p', 'hi doc-list-title', 'ऐसे पेशे जिनके लिए (उम्र/लिंग चाहे जो भी हों) फिलहाल कोई योजना कभी पात्र नहीं बनती:'));
    headlineEl.appendChild(list);
  } else {
    headlineEl.appendChild(el('p', 'hi citation', 'फिलहाल कोई भी पेशा ऐसा नहीं मिला जो अकेले (उम्र/लिंग के साथ) हर योजना से स्थायी रूप से बाहर कर दे।'));
  }
}

init();
